"""Deterministic circuit calculators.

Every function takes ``Traced`` inputs and returns ``Traced`` outputs whose
provenance lists the inputs it was derived from, so the chain
requirement -> calculation -> component value is auditable.
:data:`CALCULATORS` maps each calculator's tool id (the ``Provenance.tool``
it writes) to the callable and the order of its inputs, so
:func:`recompute_parameters` can re-run any derived parameter from the IR
(the CALCULATION stage, ``calc.recompute``).

:mod:`ai_eda.tools.calc.si` parses and formats SPICE numbers with ngspice's
scale-factor semantics (``m`` = milli, ``meg`` = mega).
:mod:`ai_eda.tools.calc.quantity` reads engineering quantities from
requirement text (``M`` = mega, units required, never guessed).
:mod:`ai_eda.tools.calc.part_value` writes the readable part value
(``Component.value``: KiCad style, 5 significant digits, ``100n``) and reads
it back with the quantity parser to compare within that display rounding.
:mod:`ai_eda.tools.calc.tline` holds the transmission-line calculators
(``calc.tline.*``: microstrip / stripline / edge-coupled impedance, the
inverse width and gap solutions, propagation delay, the critical length) and
reads a routed layer's geometry from the stackup (``line_geometry``).
:mod:`ai_eda.tools.calc.rf` holds the RF calculators (``calc.rf.*``: dBm / dBW /
dB levels, reflection and VSWR, L- and pi-matches, Butterworth / Chebyshev
low-pass prototypes and their attenuation, wavelengths, free-space path loss
and the link budget, kTB / noise figure / sensitivity, AM / FM bandwidths,
field strength, LC resonance and Q) and ``calc.crystal.c_for_load``. A level
in dB is never converted silently: dBm -> W only through ``calc.rf.dbm_to_w``.
:mod:`ai_eda.tools.calc.radio` holds the radio-design calculators
(``CALC_VERSION`` 0.10; 0.11 adds the top-C network between loaded ports): the frequency plan (multiplier stages and spurs,
harmonics, superhet LO / image / half-IF / second image / LO-spur responses),
the FM 99 % bandwidth (Bessel) and the PM-to-FM integrator, varactor and
phase-modulator tank (its exact network phase), the top-C coupled-resonator
network (element values and its exact S21), the C0-aware crystal ladder (which
refuses a bandwidth its crystals cannot give), Cohn's dissipation loss, pi
pads, the PA load line, the lumped lambda/4, the quadrature tank's exact
phase, audio emphasis / first-order / integrator / Sallen-Key terms, the 4060
time-out, the rail budget and the regulator headroom - every network
evaluated by pure-Python complex arithmetic.
"""

from ai_eda.tools.calc.basic import (
    CALC_VERSION,
    ROLE_UNITS,
    ROLES,
    astable_c_for_frequency,
    astable_frequency,
    astable_tran_start,
    astable_tran_step,
    astable_tran_stop,
    astable_v_be_reverse,
    clock_divided,
    crystal_load_capacitance,
    current_from_voltage_resistance,
    divider_r1_for_v_out,
    ipc2221_width_for_current,
    junction_temperature,
    lc_cutoff,
    led_current,
    led_series_resistor,
    parallel_resistance,
    power_from_voltage_current,
    power_from_voltage_resistance,
    rc_ac_fstart,
    rc_ac_fstop,
    rc_lowpass_magnitude,
    rc_lowpass_phase_deg,
    rc_r_for_cutoff,
    rc_step_response,
    rc_time_constant,
    rc_tran_step,
    rc_tran_stop,
    regulator_dissipation,
    voltage_divider_output,
    voltage_divider_ratio,
)
from ai_eda.tools.calc.part_value import (
    PART_VALUE_DIGITS,
    PART_VALUE_VERSION,
    display_tolerance,
    format_part_value,
    parse_part_value,
    part_value_agrees,
)
from ai_eda.tools.calc.quantity import (
    PREFIX_EXPONENTS,
    PREFIXABLE_UNITS,
    QUANTITY_VERSION,
    UNITS,
    Quantity,
    QuantityRange,
    find_quantities,
    format_quantity,
    parse_answer,
    parse_quantity,
    parse_unit,
)
from ai_eda.tools.calc.radio import (
    RADIO_CALCULATORS,
    CrystalLadder,
    TopCNetwork,
    attenuator_pi_r_series,
    attenuator_pi_r_shunt,
    bessel_j_values,
    bjt_bias_ic,
    bpf_dissipation_loss,
    butterworth_q,
    crystal_ladder,
    db_sum,
    double_tuned_rejection,
    emphasis_corner,
    emphasis_db_at,
    fm_obw99,
    fm_pm_drive_limit,
    fm_pm_integrator_tau,
    harmonic,
    highpass1_db_at,
    ladder_c_couple,
    ladder_center,
    ladder_k,
    ladder_mesh_c,
    ladder_q,
    ladder_r_end,
    ladder_s21_db,
    limiter_level,
    lossy_integrator_db_at,
    lowpass1_db_at,
    mult_spur,
    mult_stage,
    pa_load_line_r,
    pm_c_fixed,
    pm_k_pm,
    pm_source_r,
    pm_source_r_loaded,
    pm_tank_phase,
    pm_tank_phase_loaded,
    power_rail_budget,
    q_parallel,
    quad_phase,
    quarter_wave_lumped_c,
    quarter_wave_lumped_l,
    regulator_headroom,
    sallen_key_c1,
    sallen_key_c2,
    single_tuned_insertion_loss,
    single_tuned_rejection,
    superhet_half_if,
    superhet_image,
    superhet_lo,
    superhet_lo_spur_response,
    superhet_second_image,
    top_c_bw_for_qe,
    top_c_c_couple,
    top_c_c_shunt,
    top_c_c_tap,
    top_c_c_tap_reactive,
    top_c_network,
    top_c_port_r,
    top_c_port_x,
    top_c_ported_rel_s21_db,
    top_c_ported_s21_db,
    top_c_rel_s21_db,
    top_c_s21_db,
    tot_period,
    varactor_c_at_bias,
    varactor_dc_dv,
)
from ai_eda.tools.calc.recompute import CALCULATORS, derived_values, recompute_parameters
from ai_eda.tools.calc.rf import (
    K_B,
    RF_CALCULATORS,
    T0_K,
    LMatch,
    PiMatch,
    am_bandwidth,
    am_index_from_depth,
    am_sideband_dbc,
    am_total_power,
    bandwidth_from_q,
    butterworth_attenuation,
    butterworth_g,
    butterworth_g_values,
    chebyshev_attenuation,
    chebyshev_g,
    chebyshev_g_values,
    crystal_c_for_load,
    db_to_power_ratio,
    db_to_voltage_ratio,
    dbm_to_vpeak,
    dbm_to_w,
    dbuvm_to_vm,
    dbw_to_w,
    eirp,
    eirp_from_field,
    eirp_to_erp,
    erp,
    erp_to_eirp,
    field_strength,
    fm_carson_bandwidth,
    fm_modulation_index,
    friis_nf,
    fspl,
    gamma_mag,
    lambda_g,
    lc_c_for_resonance,
    lc_l_for_resonance,
    link_margin,
    lmatch,
    lmatch_highpass_c_series,
    lmatch_highpass_l_shunt,
    lmatch_lowpass_c_shunt,
    lmatch_lowpass_l_series,
    lmatch_q,
    lpf_series_l,
    lpf_shunt_c,
    mismatch_loss,
    noise_floor,
    pi_match,
    pimatch_c_load,
    pimatch_c_source,
    pimatch_l_series,
    power_ratio_to_db,
    ppm_offset,
    q_series,
    quarter_wave,
    received_power,
    return_loss,
    sensitivity,
    thermal_noise,
    vm_to_dbuvm,
    voltage_ratio_to_db,
    vswr,
    w_to_dbm,
    w_to_dbw,
    wavelength,
)
from ai_eda.tools.calc.tline import (
    LineGeometry,
    TLineRangeError,
    critical_length,
    edge_coupled_microstrip,
    edge_coupled_z_diff,
    edge_coupled_z_even,
    edge_coupled_z_odd,
    line_delay,
    line_geometry,
    microstrip,
    microstrip_e_eff,
    microstrip_z0,
    spacing_for_zdiff,
    stripline_impedance,
    stripline_z0,
    tpd,
    width_for_z0,
    width_for_z0_microstrip,
    width_for_z0_stripline,
    width_for_zdiff,
)
from ai_eda.tools.calc.si import (
    MIL_FACTOR,
    NGSPICE_EXACT_MANTISSA,
    NGSPICE_EXPONENT_RANGE,
    SI_VERSION,
    SPICE_SCALE_EXPONENTS,
    format_spice_number,
    ngspice_reads,
    parse_spice_number,
    spice_value,
)

__all__ = [
    "CALCULATORS",
    "CALC_VERSION",
    "LineGeometry",
    "TLineRangeError",
    "MIL_FACTOR",
    "NGSPICE_EXACT_MANTISSA",
    "NGSPICE_EXPONENT_RANGE",
    "PART_VALUE_DIGITS",
    "PART_VALUE_VERSION",
    "PREFIXABLE_UNITS",
    "PREFIX_EXPONENTS",
    "QUANTITY_VERSION",
    "Quantity",
    "QuantityRange",
    "ROLES",
    "ROLE_UNITS",
    "SI_VERSION",
    "SPICE_SCALE_EXPONENTS",
    "UNITS",
    "astable_c_for_frequency",
    "astable_frequency",
    "astable_tran_start",
    "astable_tran_step",
    "astable_tran_stop",
    "astable_v_be_reverse",
    "clock_divided",
    "critical_length",
    "crystal_load_capacitance",
    "current_from_voltage_resistance",
    "derived_values",
    "display_tolerance",
    "divider_r1_for_v_out",
    "edge_coupled_microstrip",
    "edge_coupled_z_diff",
    "edge_coupled_z_even",
    "edge_coupled_z_odd",
    "find_quantities",
    "ipc2221_width_for_current",
    "format_part_value",
    "format_quantity",
    "format_spice_number",
    "junction_temperature",
    "lc_cutoff",
    "led_current",
    "led_series_resistor",
    "line_delay",
    "line_geometry",
    "microstrip",
    "microstrip_e_eff",
    "microstrip_z0",
    "ngspice_reads",
    "parallel_resistance",
    "parse_answer",
    "parse_part_value",
    "parse_quantity",
    "parse_spice_number",
    "parse_unit",
    "part_value_agrees",
    "power_from_voltage_current",
    "power_from_voltage_resistance",
    "rc_ac_fstart",
    "rc_ac_fstop",
    "rc_lowpass_magnitude",
    "rc_lowpass_phase_deg",
    "rc_r_for_cutoff",
    "rc_step_response",
    "rc_time_constant",
    "rc_tran_step",
    "rc_tran_stop",
    "recompute_parameters",
    "regulator_dissipation",
    "spacing_for_zdiff",
    "spice_value",
    "stripline_impedance",
    "stripline_z0",
    "tpd",
    "voltage_divider_output",
    "voltage_divider_ratio",
    "width_for_z0",
    "width_for_z0_microstrip",
    "width_for_z0_stripline",
    "width_for_zdiff",
    "K_B",
    "RF_CALCULATORS",
    "T0_K",
    "LMatch",
    "PiMatch",
    "am_bandwidth",
    "am_index_from_depth",
    "am_sideband_dbc",
    "am_total_power",
    "bandwidth_from_q",
    "butterworth_attenuation",
    "butterworth_g",
    "butterworth_g_values",
    "chebyshev_attenuation",
    "chebyshev_g",
    "chebyshev_g_values",
    "crystal_c_for_load",
    "db_to_power_ratio",
    "db_to_voltage_ratio",
    "dbm_to_vpeak",
    "dbm_to_w",
    "dbuvm_to_vm",
    "dbw_to_w",
    "eirp",
    "eirp_from_field",
    "eirp_to_erp",
    "erp",
    "erp_to_eirp",
    "field_strength",
    "fm_carson_bandwidth",
    "fm_modulation_index",
    "friis_nf",
    "fspl",
    "gamma_mag",
    "lambda_g",
    "lc_c_for_resonance",
    "lc_l_for_resonance",
    "link_margin",
    "lmatch",
    "lmatch_highpass_c_series",
    "lmatch_highpass_l_shunt",
    "lmatch_lowpass_c_shunt",
    "lmatch_lowpass_l_series",
    "lmatch_q",
    "lpf_series_l",
    "lpf_shunt_c",
    "mismatch_loss",
    "noise_floor",
    "pi_match",
    "pimatch_c_load",
    "pimatch_c_source",
    "pimatch_l_series",
    "power_ratio_to_db",
    "ppm_offset",
    "q_series",
    "quarter_wave",
    "received_power",
    "return_loss",
    "sensitivity",
    "thermal_noise",
    "vm_to_dbuvm",
    "voltage_ratio_to_db",
    "vswr",
    "w_to_dbm",
    "w_to_dbw",
    "wavelength",
    "RADIO_CALCULATORS",
    "CrystalLadder",
    "TopCNetwork",
    "attenuator_pi_r_series",
    "attenuator_pi_r_shunt",
    "bessel_j_values",
    "bjt_bias_ic",
    "bpf_dissipation_loss",
    "butterworth_q",
    "crystal_ladder",
    "db_sum",
    "double_tuned_rejection",
    "emphasis_corner",
    "emphasis_db_at",
    "fm_obw99",
    "fm_pm_drive_limit",
    "fm_pm_integrator_tau",
    "harmonic",
    "highpass1_db_at",
    "ladder_c_couple",
    "ladder_center",
    "ladder_k",
    "ladder_mesh_c",
    "ladder_q",
    "ladder_r_end",
    "ladder_s21_db",
    "limiter_level",
    "lossy_integrator_db_at",
    "lowpass1_db_at",
    "mult_spur",
    "mult_stage",
    "pa_load_line_r",
    "pm_c_fixed",
    "pm_k_pm",
    "pm_source_r",
    "pm_source_r_loaded",
    "pm_tank_phase",
    "pm_tank_phase_loaded",
    "power_rail_budget",
    "q_parallel",
    "quad_phase",
    "quarter_wave_lumped_c",
    "quarter_wave_lumped_l",
    "regulator_headroom",
    "sallen_key_c1",
    "sallen_key_c2",
    "single_tuned_insertion_loss",
    "single_tuned_rejection",
    "superhet_half_if",
    "superhet_image",
    "superhet_lo",
    "superhet_lo_spur_response",
    "superhet_second_image",
    "top_c_bw_for_qe",
    "top_c_c_couple",
    "top_c_c_shunt",
    "top_c_c_tap",
    "top_c_c_tap_reactive",
    "top_c_network",
    "top_c_port_r",
    "top_c_port_x",
    "top_c_ported_rel_s21_db",
    "top_c_ported_s21_db",
    "top_c_rel_s21_db",
    "top_c_s21_db",
    "tot_period",
    "varactor_c_at_bias",
    "varactor_dc_dv",
]
